name: Output GitHub Context

on: workflow_dispatch

jobs:
  print-context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Print GitHub context as JSON
        run: |
          echo '${{ toJSON(github) }}'
