name: Output GitHub Context

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Output github context
        run: |
          echo '${{ toJSON(github) }}'
